// Generated by https://quicktype.io

export interface MyStats {
    SessionId: string
    SessionAddress: string
    IPAddress: string
    TotalBytesTransmitted: number
    CurrentPayloadBytes: number
    CurrentBurstBandwidth: number
    CurrentAvgBandwidth: number
    ConnectedSince: string
    IcyMetaData: boolean
    HttpVersion: string
    RequestHeaders: string
    UserAgent: string
    RequestQueryString: string
    CurrentItem: string
    VirtualBufferSeconds: number
    CurrentTrack: CurrentTrack
    GeoIPCountry: string
    GeoIPCity: string
    GeoIPZip: string
    GeoIPLatitude: number
    GeoIPLongitude: number
    Codec: string
    Quality: string
    StreamingSessionType: string
    StreamMount: string
    StreamId: string
    PrevSessionId: string
    LastUpdate: string
    OSMReverseResponse: null
    FacebookInfo: null
    StreaMonkeyListenerId: string
    AdswizzListenerId: string
    AdswizzSessionId: string
    StreamingHost: string
    PCR: number
    AdvertisementDuration: number
    CellularConnection: boolean
    ReverseDNSLookup: string
    TLD: string
    WorkerPid: string
    URL: string
    HTTPS: boolean
    NextPossibleInstreamAd: string
    InstreamGracetimeSeconds2: number
}

export interface CurrentTrack {
    TrackId: number
    Bitrate: number
    Duration: number
    StoragePath: string
    StorageType: string
    Title: string
    Artist: string
    Album: string
    Year: null
    Track: null
    Genre: string
    ArtworkPath: string
    TrackType: string
    RawTrackAccessUrl: string
    EncodingFinished: boolean
    EncodingHadError: boolean
}

export interface SocketMeta {
    artist: string
    class: string
    companion_ad: null
    cover_data: null
    cover_url: string
    master_id: string
    start_time_unix: string
    title: string
    title_combined: string
}